
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module de10_starter(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
    wire button_pushed1;
	wire button_pushed2;
    reg led0;
	reg led1;
	reg led2;
	reg led3;
	reg led4;
	reg led5;
	reg led6;
	reg led7;
	reg led8;
	reg led9;


//=======================================================
//  Structural coding
//=======================================================

    assign button_pushed1 = KEY[0];
	assign button_pushed2 = KEY[1];

    assign LEDR = {led0, led1, led2, led3, led4, led5, led6, led7, led8, led9};

    always @(button_pushed1 or button_pushed2) begin
	    if (button_pushed1) begin
			led1 <= 1'b1;
			led3 <= 1'b1;
			led5 <= 1'b1;
			led7 <= 1'b1;
			led9 <= 1'b1;
        end
		else begin
			led1 <= 1'b0;
			led3 <= 1'b0;
			led5 <= 1'b0;
			led7 <= 1'b0;
			led9 <= 1'b0;
		end

		if (button_pushed2) begin
			led0 <= 1'b1;
			led2 <= 1'b1;
			led4 <= 1'b1;
			led6 <= 1'b1;
			led8 <= 1'b1;
        end
		else begin
			led0 <= 1'b0;
			led2 <= 1'b0;
			led4 <= 1'b0;
			led6 <= 1'b0;
			led8 <= 1'b0;
		end
	end
endmodule
