
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module de10_starter(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
    wire button_pushed;
    reg led0;
	reg led1;
	reg led2;
	reg led3;
	reg led4;
	reg led5;
	reg led6;
	reg led7;
	reg led8;
	reg led9;


//=======================================================
//  Structural coding
//=======================================================

    assign button_pushed = KEY[0] | KEY[1];

    assign LEDR = {led0, led1, led2, led3, led4, led5, led6, led7, led8, led9}

    always @(button_pushed) begin
	    if (button_pushed) begin
		    {led0, led2, led4, led6, led8} = 5'b0;
			{led1, led3, led5, led7, led9} = 5'b1;
        end
		else begin
			{led0, led2, led4, led6, led8} = 5'b1;
			{led1, led3, led5, led7, led9} = 5'b0;
		end
	end
endmodule
